/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#EFF3EA',
        'surface-dim': '#DBE1D6',
        'surface-bright': '#F7FAF3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F4F7F1',
        'surface-container': '#EFF3EA',
        'surface-container-high': '#E5EAE0',
        'surface-container-highest': '#DBE1D6',
        'on-surface': '#1A2F16',
        'on-surface-variant': '#43523F',
        'inverse-surface': '#2E342D',
        'inverse-on-surface': '#F4F7F1',
        outline: '#BAC7B8',
        'outline-variant': '#DCE2DA',
        'surface-tint': '#2C5E2E',
        primary: '#2C5E2E',
        'on-primary': '#ffffff',
        'primary-container': '#D8EAD6',
        'on-primary-container': '#0A230D',
        'inverse-primary': '#8EC849',
        secondary: '#5A8A3A',
        'on-secondary': '#ffffff',
        'secondary-container': '#F0F6EA',
        'on-secondary-container': '#1A2F16',
        tertiary: '#FFD700',
        'on-tertiary': '#1A2F16',
        'tertiary-container': '#FFF9C4',
        'on-tertiary-container': '#564400',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#D8EAD6',
        'primary-fixed-dim': '#B5D1B2',
        'on-primary-fixed': '#0A230D',
        'on-primary-fixed-variant': '#1F4721',
        background: '#F7FAF3',
        'on-background': '#1A2F16',
        'surface-variant': '#EFF3EA',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(52, 103, 57, 0.05)',
        md: '0 4px 6px rgba(52, 103, 57, 0.1)',
        lg: '0 10px 15px -3px rgba(52, 103, 57, 0.1), 0 4px 6px -2px rgba(52, 103, 57, 0.05)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
    },
  },
}