/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbfcdb',
        'surface-dim': '#dbdcbd',
        'surface-bright': '#fbfcdb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f6d5',
        'surface-container': '#eff0d0',
        'surface-container-high': '#e9eaca',
        'surface-container-highest': '#e3e5c5',
        'on-surface': '#1b1d09',
        'on-surface-variant': '#42493f',
        'inverse-surface': '#30321c',
        'inverse-on-surface': '#f2f3d2',
        outline: '#72796e',
        'outline-variant': '#c1c9bb',
        'surface-tint': '#386934',
        primary: '#386934',
        'on-primary': '#ffffff',
        'primary-container': '#91c788',
        'on-primary-container': '#235422',
        'inverse-primary': '#9ed494',
        secondary: '#466641',
        'on-secondary': '#ffffff',
        'secondary-container': '#c7edbe',
        'on-secondary-container': '#4c6c47',
        tertiary: '#4a6632',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a3c385',
        'on-tertiary-container': '#36511f',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b9f1ae',
        'primary-fixed-dim': '#9ed494',
        'on-primary-fixed': '#002203',
        'on-primary-fixed-variant': '#20511f',
        'secondary-fixed': '#c7edbe',
        'secondary-fixed-dim': '#acd0a3',
        'on-secondary-fixed': '#032105',
        'on-secondary-fixed-variant': '#2f4e2c',
        'tertiary-fixed': '#ccedac',
        'tertiary-fixed-dim': '#b0d192',
        'on-tertiary-fixed': '#0c2000',
        'on-tertiary-fixed-variant': '#334e1d',
        background: '#fbfcdb',
        'on-background': '#1b1d09',
        'surface-variant': '#e3e5c5',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(82, 115, 77, 0.05)',
        md: '0 4px 6px rgba(82, 115, 77, 0.1)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
}