/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#F2EDC2',
        'surface-dim': '#e3deaf',
        'surface-bright': '#F2EDC2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fafaf8',
        'surface-container': '#F2EDC2',
        'surface-container-high': '#e9e4b7',
        'surface-container-highest': '#e0dbad',
        'on-surface': '#346739',
        'on-surface-variant': '#4a5d4e',
        'inverse-surface': '#263328',
        'inverse-on-surface': '#F2EDC2',
        outline: '#9FCB98',
        'outline-variant': '#b5deb0',
        'surface-tint': '#79AE6F',
        primary: '#346739',
        'on-primary': '#ffffff',
        'primary-container': '#79AE6F',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#9FCB98',
        secondary: '#79AE6F',
        'on-secondary': '#ffffff',
        'secondary-container': '#9FCB98',
        'on-secondary-container': '#1e3d21',
        tertiary: '#9FCB98',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c5efc0',
        'on-tertiary-container': '#264229',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#9FCB98',
        'primary-fixed-dim': '#79AE6F',
        'on-primary-fixed': '#122615',
        'on-primary-fixed-variant': '#234a26',
        background: '#fafaf8',
        'on-background': '#346739',
        'surface-variant': '#F2EDC2',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        sm: '0 1px 2px rgba(52, 103, 57, 0.05)',
        md: '0 4px 6px rgba(52, 103, 57, 0.1)',
        lg: '0 10px 15px -3px rgba(52, 103, 57, 0.1), 0 4px 6px -2px rgba(52, 103, 57, 0.05)',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
    },
  },
}